#!/usr/bin/env bash
# Build prompt.md by concatenating prompts listed in $DAISY_HOME/include.txt
# Usage: build-prompt.sh

set -e

# Validate environment
if [ -z "$DAISY_ROOT" ]; then
    echo "Error: DAISY_ROOT not set" >&2
    exit 1
fi

if [ -z "$DAISY_HOME" ]; then
    echo "Error: DAISY_HOME not set" >&2
    exit 1
fi

# Check for include.txt
INCLUDE_FILE="$DAISY_HOME/include.txt"
if [ ! -f "$INCLUDE_FILE" ]; then
    echo "Error: $INCLUDE_FILE not found" >&2
    echo "Create include.txt in your home directory listing prompts to include" >&2
    exit 1
fi

# Output file
OUTPUT_FILE="$DAISY_ROOT/prompt.md"

# Temporary file for building
TEMP_FILE="$(mktemp)"

# Trap to clean up temp file
trap 'rm -f "$TEMP_FILE"' EXIT

# Get current timestamp
TIMESTAMP=$(date +"%Y-%m-%d %H:%M %Z")

# Get home name from DAISY_HOME path
HOME_NAME=$(basename "$DAISY_HOME")

# Write header
cat > "$TEMP_FILE" <<EOF
# Daisy Prompt - Auto-generated
# Home: $HOME_NAME
# Built: $TIMESTAMP
# Source: $DAISY_HOME/include.txt
#
# This file is generated by scripts/build-prompt.sh
# Do not edit directly - edit source prompts in prompts/ directory
# To rebuild: \$DAISY_ROOT/scripts/build-prompt.sh

EOF

# Track included prompts
INCLUDED_PROMPTS=()

# Read include.txt and process each prompt
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    
    # Trim whitespace
    prompt_name=$(echo "$line" | xargs)
    
    # Skip if empty after trimming
    [ -z "$prompt_name" ] && continue
    
    # Resolve prompt path
    prompt_path="$DAISY_ROOT/prompts/${prompt_name}.md"
    
    # Check if prompt exists
    if [ ! -f "$prompt_path" ]; then
        echo "Warning: Prompt not found: $prompt_path" >&2
        echo "# ============================================================" >> "$TEMP_FILE"
        echo "# ERROR: Prompt '$prompt_name' not found" >> "$TEMP_FILE"
        echo "# Expected: $prompt_path" >> "$TEMP_FILE"
        echo "# ============================================================" >> "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"
        continue
    fi
    
    # Add separator and prompt content
    echo "" >> "$TEMP_FILE"
    echo "# ============================================================" >> "$TEMP_FILE"
    echo "# Prompt: $prompt_name" >> "$TEMP_FILE"
    echo "# Source: prompts/${prompt_name}.md" >> "$TEMP_FILE"
    echo "# ============================================================" >> "$TEMP_FILE"
    echo "" >> "$TEMP_FILE"
    
    # Append prompt content
    cat "$prompt_path" >> "$TEMP_FILE"
    
    # Track this prompt
    INCLUDED_PROMPTS+=("$prompt_name")
    
done < "$INCLUDE_FILE"

# Move temp file to output
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Report success
echo "✅ Built prompt.md for home: $HOME_NAME"
echo "   Included: ${INCLUDED_PROMPTS[*]}"
echo "   Output: $OUTPUT_FILE"
echo "   Size: $(wc -l < "$OUTPUT_FILE") lines"

exit 0
