#!/usr/bin/env bash
# Build AGENTS.md for a home by concatenating prompts listed in include.txt
# Usage: build-prompt.sh [home-name]
#
# If home-name is provided, builds for that home.
# Otherwise resolves via .daisy/home or $DAISY_HOME.
#
# Output: home/{home}/AGENTS.md
#
# Supports two include modes:
#   daisy          - Full prompt included in AGENTS.md
#   ~retrospective - Lazy: only ## Trigger section included, rest loaded on demand

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/daisy/common.sh"

require_root

# Resolve which home to build for
if [ -n "$1" ]; then
    DAISY_HOME_NAME="$1"
    DAISY_HOME="$DAISY_ROOT/home/$DAISY_HOME_NAME"
    if [ ! -d "$DAISY_HOME" ]; then
        echo "Error: Home '$DAISY_HOME_NAME' not found at $DAISY_HOME" >&2
        exit 1
    fi
else
    resolve_home || exit 1
fi

# Check for include.txt
INCLUDE_FILE="$DAISY_HOME/include.txt"
if [ ! -f "$INCLUDE_FILE" ]; then
    echo "Error: $INCLUDE_FILE not found" >&2
    echo "Create include.txt in your home directory listing prompts to include" >&2
    exit 1
fi

# Output file (per-home)
OUTPUT_FILE="$DAISY_HOME/AGENTS.md"

# Temporary file for building
TEMP_FILE="$(mktemp)"

# Trap to clean up temp file
trap 'rm -f "$TEMP_FILE"' EXIT

# Get current timestamp
TIMESTAMP=$(date +"%Y-%m-%d %H:%M %Z")

# Write header
cat > "$TEMP_FILE" <<EOF
# Daisy Prompt - Auto-generated
# Home: $DAISY_HOME_NAME
# Built: $TIMESTAMP
# Source: home/$DAISY_HOME_NAME/include.txt
#
# This file is generated by scripts/build-prompt.sh
# Output: home/$DAISY_HOME_NAME/AGENTS.md
# Do not edit directly - edit source prompts in prompts/ directory
# To rebuild: \$DAISY_ROOT/scripts/build-prompt.sh $DAISY_HOME_NAME

EOF

# Track included prompts
FULL_PROMPTS=()
LAZY_PROMPTS=()

# Extract trigger section from a prompt file (everything from ## Trigger to next heading)
extract_trigger() {
    local file="$1"
    awk '
        /^## Trigger/ { found=1; next }
        found && /^#/ { exit }
        found { print }
    ' "$file"
}

# Read include.txt and process each prompt
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue

    # Trim whitespace
    line=$(echo "$line" | xargs)

    # Skip if empty after trimming
    [ -z "$line" ] && continue

    # Check for lazy prefix (~)
    LAZY=false
    prompt_name="$line"
    if [[ "$line" =~ ^~ ]]; then
        LAZY=true
        prompt_name="${line#\~}"
    fi

    # Resolve prompt path
    prompt_path="$DAISY_ROOT/prompts/${prompt_name}.md"

    # Check if prompt exists
    if [ ! -f "$prompt_path" ]; then
        echo "Warning: Prompt not found: $prompt_path" >&2
        echo "# ============================================================" >> "$TEMP_FILE"
        echo "# ERROR: Prompt '$prompt_name' not found" >> "$TEMP_FILE"
        echo "# Expected: $prompt_path" >> "$TEMP_FILE"
        echo "# ============================================================" >> "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"
        continue
    fi

    if [ "$LAZY" = true ]; then
        # Lazy mode: extract only the ## Trigger section
        trigger_content=$(extract_trigger "$prompt_path")

        if [ -z "$trigger_content" ]; then
            echo "Warning: No ## Trigger section found in $prompt_path" >&2
            echo "  Include as full prompt instead, or add a ## Trigger section" >&2
            echo "" >> "$TEMP_FILE"
            echo "# ============================================================" >> "$TEMP_FILE"
            echo "# Prompt: $prompt_name (WARNING: no trigger section, included in full)" >> "$TEMP_FILE"
            echo "# Source: prompts/${prompt_name}.md" >> "$TEMP_FILE"
            echo "# ============================================================" >> "$TEMP_FILE"
            echo "" >> "$TEMP_FILE"
            cat "$prompt_path" >> "$TEMP_FILE"
            FULL_PROMPTS+=("$prompt_name")
        else
            echo "" >> "$TEMP_FILE"
            echo "# ============================================================" >> "$TEMP_FILE"
            echo "# Prompt: $prompt_name (lazy - read full prompt when triggered)" >> "$TEMP_FILE"
            echo "# Source: prompts/${prompt_name}.md" >> "$TEMP_FILE"
            echo "# ============================================================" >> "$TEMP_FILE"
            echo "" >> "$TEMP_FILE"
            echo "$trigger_content" >> "$TEMP_FILE"
            LAZY_PROMPTS+=("$prompt_name")
        fi
    else
        # Full mode: include entire prompt
        echo "" >> "$TEMP_FILE"
        echo "# ============================================================" >> "$TEMP_FILE"
        echo "# Prompt: $prompt_name" >> "$TEMP_FILE"
        echo "# Source: prompts/${prompt_name}.md" >> "$TEMP_FILE"
        echo "# ============================================================" >> "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"
        cat "$prompt_path" >> "$TEMP_FILE"
        FULL_PROMPTS+=("$prompt_name")
    fi

done < "$INCLUDE_FILE"

# Move temp file to output
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Report success
echo "✅ Built AGENTS.md for home: $DAISY_HOME_NAME"
if [ ${#FULL_PROMPTS[@]} -gt 0 ]; then
    echo "   Full: ${FULL_PROMPTS[*]}"
fi
if [ ${#LAZY_PROMPTS[@]} -gt 0 ]; then
    echo "   Lazy: ${LAZY_PROMPTS[*]}"
fi
echo "   Output: $OUTPUT_FILE"
echo "   Size: $(wc -l < "$OUTPUT_FILE") lines"

exit 0
